{
    'name': 'Billing Accounts (Worktags)',
    'version': '18.0.6.0.0',
    'summary': 'Adds worktags, billing report and invoice management',
    'author': 'Your Name',
    'license': 'LGPL-3',
    'category': 'Accounting',
    'depends': [
        'analytic',
        'account',
        'sale',
        'product',
        'techservices_groups',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/labor_products.xml',
        'views/service_worktag_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/worktag_billing_report_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
