[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_dev_password
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
dev_mode = reload,qweb,werkzeug,xml
workers = 0
max_cron_threads = 1
log_level = info
http_port = 8069
dbfilter = .*
list_db = True
admin_passwd = $pbkdf2-sha512$600000$gLD2fg8hBEBI6X2PsTbGGA$56G/Rqz/iAYRGn3lqUZIzVwijlM9yz45KMNoRvcDVTWQf/PXJ9.p/S8S6k/nHrHRIMET/.sOFlQXrSTDCCsKFQ

