{
    'name': 'Technical Services Groups',
    'version': '18.0.1.0.0',
    'summary': 'Defines Technician, Supervisor and Manager roles for Technical Services',
    'author': 'Your Name',
    'license': 'LGPL-3',
    'category': 'Technical Services',
    'depends': [
        'base',
        'stock',
        'stock_account',
        'hr_timesheet',
        'sales_team',
        'account',
        'crm_iap_mine',
        'crm_iap_enrich',
        'sale_crm',
        'sale_management',
        'repair',
        'opportunity_display',
        'contacts',
    ],
    'data': [
        'security/techservices_groups.xml',
        'security/repair_access.xml',
        'views/crm_lead_views.xml',
        'views/repair_order_views.xml',
        'views/sale_order_views.xml',
        'views/inventory_menu_restrictions.xml',
        'views/product_template_fields.xml',
        'views/product_form_restrictions.xml',
        'views/account_move_restrictions.xml',
        'views/res_partner_views.xml',
        'views/assets.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
